// TODO: move this in each separate template
export const templates = {
  "wordpress-and-node-app": {
    PROJECT_NAME: "%%PROJECT_NAME%%",
    REPOSITORY_NAME: "%%REPOSITORY_NAME%%",
    WORDPRESS_API_URL: "%%WORDPRESS_API_URL%%",
    MYSQL_DATABASE: "%%MYSQL_DATABASE%%"
  },
  "wordpress-and-traefik": {
    PROJECT_NAME: "%%PROJECT_NAME%%",
    REPOSITORY_NAME: "%%REPOSITORY_NAME%%",
    MYSQL_ROOT_PASSWORD: "%%MYSQL_ROOT_PASSWORD%%",
    MYSQL_USER: "%%MYSQL_USER%%",
    MYSQL_PASSWORD: "%%MYSQL_PASSWORD%%",
    PRODUCTION_URL: "%%PRODUCTION_URL%%"
  },
  "wordpress-and-traefik-server": {
    PROJECT_NAME: "%%PROJECT_NAME%%",
    REPOSITORY_NAME: "%%REPOSITORY_NAME%%",
    PRODUCTION_URL: "%%PRODUCTION_URL%%",
    STAGING_URL: "%%STAGING_URL%%",
    PRODUCTION_MYSQL_ROOT_PASSWORD: "%%PRODUCTION_MYSQL_ROOT_PASSWORD%%",
    PRODUCTION_MYSQL_USER: "%%PRODUCTION_MYSQL_USER%%",
    PRODUCTION_MYSQL_PASSWORD: "%%PRODUCTION_MYSQL_PASSWORD%%",
    STAGING_MYSQL_ROOT_PASSWORD: "%%STAGING_MYSQL_ROOT_PASSWORD%%",
    STAGING_MYSQL_USER: "%%STAGING_MYSQL_USER%%",
    STAGING_MYSQL_PASSWORD: "%%STAGING_MYSQL_PASSWORD%%"
  }
};
